server:
  host: "0.0.0.0"
  port: "8080"

database:
  url: "postgres://localhost/example_db"
  max_connections: 10

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

worker:
  concurrency: 5
  queue_name: "default"

log:
  level: "info"
  format: "text"  # text or json

env: "development"
